---
title: "DataPrep"
author: "PMagoto"
format: html
editor: visual
---

Opening the correct packages:

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
library(ggplot2) 
library(tidyverse)
library(DigitalMethodsData)
library(ggmap)
library(tidygeocoder)
library(leaflet)
library(leaflet.extras)
library(leaftime)
library(leaflet.providers)
library(spatstat)
```

Registering my Google Key:

```{r}
#register google key 
register_google(key = Sys.getenv("GOOGLE_KEY"))
```

inserting data sets and prepping them to be geo-coded:

```{r}
locations <- read.csv("locations3.csv") %>% 
  mutate(full.address = paste0(street.address,","," ", city, ",", " ", state))
entries <- read.csv("entries3.csv") %>% 
  mutate(full.address = paste0(street.address,","," ", city, ",", " ", state))
people <- read.csv("people3.csv") #no fuull address is needed
write.csv(locations, file = "locationsprepped.csv")#prep for geocode with ful address and savw locally
write.csv(entries, file = "entriesprepped.csv") #prep for geocode with ful address and savw locally
```

Geo-coding data:

```{r}
locationsprepped <- read.csv("locationsprepped.csv") %>% 
  mutate_geocode(full.address, output = "latlon", source = "google")
enttriesprepped <- read.csv("entriesprepped.csv") %>% 
  mutate_geocode(full.address, output = "latlon", source = "google")
write.csv(locationsprepped, file="locations.final.csv")
write.csv(enttriesprepped, file="entries.final.csv")
```

Creating data-frames for polygons to represent Black and White Storyville:

```{r}

```
